# Generated by Django 5.2.4 on 2026-06-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='email',
            field=models.EmailField(max_length=70),
        ),
    ]
