# Generated by Django 5.2.4 on 2026-06-10 19:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_ai', '0002_alter_query_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='next_action',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='query',
            name='priority',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='query',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
